apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: work-wechat-robot
  name: work-wechat-robot
  namespace: monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: work-wechat-robot
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: work-wechat-robot
    spec:
      containers:
      - image: truman/wechat-robot:2.0.0
        imagePullPolicy: IfNotPresent
        name: work-wechat-robot
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: work-wechat-robot
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: work-wechat-robot
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
