kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  storageClassName: "longhorn"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
